### ISSUE TITLE
error in running demo.py

### ISSUE THREAD

**Issue by kishan1823** [MengHao666/Minimal-Hand-pytorch#11]
![image](https://user-images.githubusercontent.com/65106584/121172722-9ca94580-c875-11eb-8bfb-837da8644678.png)

i am getting this issue on running demo.py. can you help me in resolving this error.

**Comment by EEWenbinWu** [comment]
you can add the following three lines: pose = pose.to(device), shape=shape.to(device), mano = mano.to(device)

**Comment by EEWenbinWu** [comment]
but then I got this new pro:
![image](https://user-images.githubusercontent.com/17973265/121175863-22d18600-c88e-11eb-87c7-f3f2f4cd9528.png)

**Comment by kishan1823** [comment]
where should i add those lines

**Comment by EEWenbinWu** [comment]
after you get yourfirst pose, shape and mano

**Comment by kishan1823** [comment]
after adding also, i am getting same error

**Comment by kishan1823** [comment]
yes the error resolved by adding those 3 lines, but a new error raised
![image](https://user-images.githubusercontent.com/65106584/121189840-1f3b0080-c888-11eb-8d00-9e900fd04d13.png)

**Comment by EEWenbinWu** [comment]
I got the same problem.

**Comment by maitetsu** [comment]
My mother tongue is not English. I'm sorry for some grammatical mistakes.

1. First of all, let me explain why the first error occurs. In the original manopth, if the pose parameter in the form of matrix, the input matrix will be SVD decomposed to ensure that these matrices must be rotation matrices. Please refer to line 165 of original "manopth/manolayer.py". 
![屏幕截图 2021-06-08 221742](https://user-images.githubusercontent.com/53359928/121201858-6be20400-c8a7-11eb-8469-478661e195cf.png)
After SVD decomposition, no matter the input pose parameter is on CPU or GPU, the output will be on GPU. In demo.py, the parameters of mano are all on the CPU, so the first error is raised.

2. My solution is to modify manopth. Specifically, modify the batch of "manopth/rotproj.py". The result of modifying can be seen here. After modification, this function can ensure that the input and output are CPU or GPU. Just add "device = rotmat.device" and change "rotmat = rotmat.cuda()" to "rotmat = rotmat.to(device)",  you can try.
![屏幕截图 2021-06-08 221944](https://user-images.githubusercontent.com/53359928/121202287-c24f4280-c8a7-11eb-8a95-80f43a7bd81a.png)

**Comment by EEWenbinWu** [comment]
thanks a lot~ And could you please help us to solve the second error. https://user-images.githubusercontent.com/65106584/121189840-1f3b0080-c888-11eb-8d00-9e900fd04d13.png

**Comment by maitetsu** [comment]
Of course, putting mano on GPU is also a solution. As for your second problem, I think it is due to the mano.th_faces on GPU. When it is on CPU, open3d can be automatically converted to the format required by open3d, but can't on GPU. Just put mano.th_faces  on CPU can fix. Like this: " mesh.triangles = open3d.utility.Vector3iVector(mano.th_faces.cpu()) "
![屏幕截图 2021-06-08 222920](https://user-images.githubusercontent.com/53359928/121204600-92a13a00-c8a9-11eb-8bbe-75f3d911f180.png)

**Comment by EEWenbinWu** [comment]
thx

**Comment by kishan1823** [comment]
thank you

**Comment by hammerstone18** [comment]
i want  to konw why i had added everthing you said  but i also can not run demo

**Comment by hammerstone18** [comment]
`  File "D:\Minimal-Hand-pytorch-main\demo.py", line 120, in <module>
    _, j3d_p0_ops = mano(pose0, opt_tensor_shape)
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Minimal-Hand-pytorch-main\manopth\manolayer.py", line 181, in forward
    th_v_shaped = torch.matmul(self.th_shapedirs,
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument mat2 in method wrapper_mm)
`

**Comment by MengHao666** [comment]
> a solution. As for your second problem, I think it is due to the mano.th_faces on GPU. When it is on CPU, open3d can be automatically converted to the format required by open3d, but can't on GPU. Just put mano.th_faces on CPU can fix. Like this: " mesh.triangles = open3d.utility.Vector3iVector(mano.th_faces.cpu()) "

it seems two arguments are not in same device, please check this issue carfully.

**Comment by hammerstone18** [comment]
> yeah i solved this problem but when running the demo.py i cannot display the plot

**Comment by MengHao666** [comment]
this might be related to version of matplotlib.---- Replied Message ***@***.***>Date04/03/2022 20:19 ***@***.***> CcRaphaël ***@***.******@***.***>SubjectRe: [MengHao666/Minimal-Hand-pytorch] error in running demo.py (#11)


yeah i solved this problem but when running the demo.py i cannot display the plot
error:PyEval_RestoreThread: the function must be called with the GIL held, but the GIL is released (the current Python thread state is NULL)

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/MengHao666/Minimal-Hand-pytorch/issues/11#issuecomment-1086855482",
"url": "https://github.com/MengHao666/Minimal-Hand-pytorch/issues/11#issuecomment-1086855482",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by qwer904** [comment]
> ` File "D:\Minimal-Hand-pytorch-main\demo.py", line 120, in <module> _, j3d_p0_ops = mano(pose0, opt_tensor_shape) File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl return forward_call(*input, **kwargs) File "D:\Minimal-Hand-pytorch-main\manopth\manolayer.py", line 181, in forward th_v_shaped = torch.matmul(self.th_shapedirs, RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument mat2 in method wrapper_mm)`

I had the same problem as you, have you solved it yet?
