### ISSUE TITLE
 cannot import name 'manolayer'

### ISSUE THREAD

**Issue by orydatadudes** [MengHao666/Minimal-Hand-pytorch#52]
i got that error after trying  to run demo.py

line 3 :from manopth import manolayer
ImportError: cannot import name 'manolayer'

under folder manopth i can see only one file (rotproj.py)

**Comment by orydatadudes** [comment]
.

**Comment by sunhaha123** [comment]
Did the problem dead?

**Comment by MengHao666** [comment]
Hi，I have not checked yet. You could find solution in the issues and readme.txt maybe.I am busy with another projects now. I would check it when I am free.Thanks.---- Replied Message ***@***.***>Date02/25/2022 18:55 ***@***.***> ***@***.***>SubjectRe: [MengHao666/Minimal-Hand-pytorch] cannot import name 'manolayer' (Issue #52)
Did the problem dead?

—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/MengHao666/Minimal-Hand-pytorch/issues/52#issuecomment-1050749775",
"url": "https://github.com/MengHao666/Minimal-Hand-pytorch/issues/52#issuecomment-1050749775",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by timegoby** [comment]
check the last line in environment.yml
